export default {
  login: "ankitharitus",
  id: 48482134,
  node_id: "MDQ6VXNlcjQ4NDgyMTM0",
  avatar_url: "https://avatars.githubusercontent.com/u/48482134?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/ankitharitus",
  html_url: "https://github.com/ankitharitus",
  followers_url: "https://api.github.com/users/ankitharitus/followers",
  following_url:
    "https://api.github.com/users/ankitharitus/following{/other_user}",
  gists_url: "https://api.github.com/users/ankitharitus/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/ankitharitus/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/ankitharitus/subscriptions",
  organizations_url: "https://api.github.com/users/ankitharitus/orgs",
  repos_url: "https://api.github.com/users/ankitharitus/repos",
  events_url: "https://api.github.com/users/ankitharitus/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/ankitharitus/received_events",
  type: "User",
  site_admin: false,
  name: "Haritus",
  company: "Nagarro",
  blog: "",
  location: "Gurgaon",
  email: null,
  hireable: null,
  bio: "Passionate front-end web developer with 3 years of experience using JavaScript, React.Js, Typescript, HTML5, SASS to build all aspects of the user experience.",
  twitter_username: "ankitharitus",
  public_repos: 7,
  public_gists: 9,
  followers: 12,
  following: 12,
  created_at: "2019-03-12T13:23:05Z",
  updated_at: "2021-09-23T12:49:51Z",
};
